### ISSUE TITLE
Remove FHEPayment contract and create FHEGasLimit.sol

### ISSUE THREAD

**Issue by immortal-tofu** [zama-ai/fhevm-backend#198]
Payment won't be used anymore.
The idea is to remove the `FHEPayment.sol` and instead of create a minimized version called `FHEGasLimit.sol`.

This contract is not part of core components anymore, but rather an extension to call in TFHEExecutor similar to:

```solidity
contract TFHEExecutorWithLimit is TFHEExecutor {
    function fheAdd(uint256 lhs, uint256 rhs, bytes1 scalarByte) public virtual override returns (uint256 result) {
        fheGasLimit.consumeGasForFheAdd(msg.sender, lhsType, scalar);
        result = super.fheAdd(lhs, rhs, scalarByte);
    }
}
```

**Comment by jatZama** [comment]
Done in #211 
With a caveat: for the moment we agreed on Slack to keep the call to FHEGasLimit by default inside the original `TFHEExecutor` contract. For two reasons: 
1/ it is critical to avoid DDOS attack to keep some limitation on number of FHE ops
2/ and otherwise we would have to maintain 4 versions of almost same contract: `TFHEExecutor` , `TFHEExecutorWithLimit`, `TFHEExecutorWithEvents` and `TFHEExecutorWithEventsWithLimit`.
