### ISSUE TITLE
Request for the improvement on the naming of errors

### ISSUE THREAD

**Issue by poppyseedDev** [zama-ai/fhevm-backend#205]
Is there a possibility to not have errors like:  "Sender doesn't own lhs on op", "Sender doesn't own rhs on op", "Sender doesn't own ct on op" but to have something more descriptive?

In the https://github.com/zama-ai/fhevm-backend/blob/main/contracts/contracts/TFHEExecutor.sol ?

**Comment by jatZama** [comment]
Just saw this, i'm not sure this issue makes sense since @PacificYield is already working on replacing error strings with custom errors in order to save gas. So maybe you should review current PR if you don't like new names. Current PR is still WIP fyi here #203  so I'm closing this one since it looks like a duplicate for me.
